<?php

/**
 * PluginAnnounce
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opAnnouncePlugin
 * @subpackage model
 * @author     Hiromi Hishida <info@77-web.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginAnnounce extends BaseAnnounce
{
  public function isPublic()
  {
    return $this->getIsPublic() && time() >= strtotime($this->getPublishDate());
  }
  
  public function getPublishDate()
  {
    if(null !== $this->_get('publish_date'))
    {
      return $this->_get('publish_date');
    }
    return $this->getCreatedAt();
  }
  
  public function isVisible($app)
  {
    return 'mobile_frontend' == $app ? $this->getIsMobile() : $this->getIsPc();
  }
  
  public function getApps()
  {
    $apps = array();
    if($this->getIsPc())
    {
      $apps[] = 'pc';
    }
    if($this->getIsMobile())
    {
      $apps[] = 'mobile';
    }
    return $apps;
  }
}