<?php

/**
 * PluginAnnounceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAnnounceTable extends Doctrine_Table
{
  public function getAppPublicPager($isMember, $app, $size, $page = 1)
  {
    $query = $this->createPublicQuery($app, 'a');
    if(!$isMember)
    {
      $query->addWhere('a.is_secure = ?', false);
    }
    
    return $this->generatePager($query, $size, $page);
  }

  public function getPager($size, $page)
  {
    $query = $this->createQuery('a')->orderBy('a.updated_at DESC');
    
    return $this->generatePager($query, $size, $page);
  }
  
  protected function generatePager($query, $size, $page)
  {
    $pager = new sfDoctrinePager('Announce', $size);
    $pager->setQuery($query);
    $pager->setPage($page);
    $pager->init();
    
    return $pager;
  }
  
  public function getLatest($app, $limit = 5)
  {
    return $this->createPublicQuery($app, 'a')->limit($limit)->execute();
  }
  
  protected function createPublicQuery($app, $alias = 'a')
  {
    $appField = 'mobile_frontend' == $app ? 'is_mobile' : 'is_pc';
    return $this->createQuery('a')->addWhere('a.'.$appField.' = ?', true)->addWhere('a.is_public = ? AND (a.publish_date <= ? OR a.publish_date IS NULL)', array(true, date('Y-m-d H:i:s')))->orderBy('a.publish_date DESC, a.created_at DESC');
  }
}